### ISSUE TITLE
change to correct Email

### ISSUE THREAD

**Issue by aAYUSHkujur** [SmartGen-ai/smartgenai#4]
### **Change in these two places.**
1. ![image](https://github.com/SmartGen-ai/smartgenai/assets/73094905/351553be-5ca7-498d-8642-83526869c07d)

2. ### ![image](https://github.com/SmartGen-ai/smartgenai/assets/73094905/813da5af-d2aa-4a9e-9b26-6c31f210b68a)

**Comment by Sjsan69** [comment]
Asked her 
she will be sending by night

**Comment by aAYUSHkujur** [comment]
and also her's socials.
